hummingbird.startHummingbird()
basic.forever(function () {
    basic.showString("Gabe, Jr.")
    basic.showIcon(IconNames.Rollerskate)
    basic.pause(100)
    basic.showIcon(IconNames.Butterfly)
    basic.pause(100)
    basic.showIcon(IconNames.StickFigure)
    basic.pause(100)
    basic.clearScreen()
    hummingbird.setLED(ThreePort.One, 0)
    hummingbird.setLED(ThreePort.Two, 100)
    basic.pause(1000)
    hummingbird.setLED(ThreePort.One, 73)
    hummingbird.setLED(ThreePort.Two, 0)
    basic.pause(1000)
})
